# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WhatsNextIOS' do
pod 'AFNetworking', '~> 3.0'
pod 'Fabric'
pod 'Crashlytics'
pod "MagicalRecord"
pod 'AFOAuth2Manager', :git => 'https://github.com/AFNetworking/AFOAuth2Manager.git', :branch => '3_0_0_branch'
pod 'iOS-Slide-Menu'
pod 'UIScrollView-InfiniteScroll'
pod 'JSONModel'
pod 'Selene'
pod "MBCircularProgressBar"
pod "BLMultiColorLoader"
pod 'XHAmazingLoading'
pod "SwiftSpinner"
pod "LinearProgressBar"
pod 'YLProgressBar', '~> 3.8.0'
pod 'EAColourfulProgressView', '~> 0.1.0'
pod 'BPForms'
pod 'CWStatusBarNotification', '~> 2.3.4'
end

target 'WhatsNextIOSTests' do

end

target 'WhatsNextIOSUITests' do

end

